import "./globals.css";
import type { Metadata } from "next";
import { Inter } from "next/font/google";
import AdminHeader from "@/components/AdminHeader";

const inter = Inter({ subsets: ["latin"] });

export const metadata: Metadata = {
  title: "Vijay Brother admin.in",
  description: "Generated by Macaly",
};

export default function RootLayout({
  children,
}: {
  children: React.ReactNode;
}) {
  return (
    <html lang="en">
      <body className={inter.className}>
        <AdminHeader />
        {children}
      </body>
    </html>
  );
}